// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr8JDQ_dJCg1gZ07ahwQAUJLf3p-Dohpc',
    appId: '1:441881788885:web:f735557db3bb440af87d5c',
    messagingSenderId: '441881788885',
    projectId: 'posefit-964dd',
    authDomain: 'posefit-964dd.firebaseapp.com',
    storageBucket: 'posefit-964dd.firebasestorage.app',
    measurementId: 'G-CX0SSPCG8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFGddZ4nAaNWipyt6wKVkheQIk2-d4hjk',
    appId: '1:441881788885:android:1a6147fdeef4ad94f87d5c',
    messagingSenderId: '441881788885',
    projectId: 'posefit-964dd',
    storageBucket: 'posefit-964dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHZkXTr0Wcu7YS0kAyHyzgA3kTtKl4P0',
    appId: '1:441881788885:ios:dca71aa895a9cc35f87d5c',
    messagingSenderId: '441881788885',
    projectId: 'posefit-964dd',
    storageBucket: 'posefit-964dd.firebasestorage.app',
    iosBundleId: 'com.example.posefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASHZkXTr0Wcu7YS0kAyHyzgA3kTtKl4P0',
    appId: '1:441881788885:ios:dca71aa895a9cc35f87d5c',
    messagingSenderId: '441881788885',
    projectId: 'posefit-964dd',
    storageBucket: 'posefit-964dd.firebasestorage.app',
    iosBundleId: 'com.example.posefit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr8JDQ_dJCg1gZ07ahwQAUJLf3p-Dohpc',
    appId: '1:441881788885:web:842a8e9c72d49912f87d5c',
    messagingSenderId: '441881788885',
    projectId: 'posefit-964dd',
    authDomain: 'posefit-964dd.firebaseapp.com',
    storageBucket: 'posefit-964dd.firebasestorage.app',
    measurementId: 'G-MCLEKXDE6W',
  );
}
